# Generated by Django 5.2 on 2025-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
