# Generated by Django 5.2 on 2025-06-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
