# Generated by Django 5.2 on 2025-05-05 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="all_rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="monthly_rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="total_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="wallet_field",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="weekly_rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_token",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
