# Generated by Django 5.2 on 2025-05-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_password_delete_userprofile"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
