# Generated by Django 5.2 on 2025-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
