# Generated by Django 5.2 on 2025-05-03 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet", old_name="TotalBalance", new_name="total_balance",
        ),
        migrations.RenameField(
            model_name="wallet", old_name="User_id", new_name="user_id_fk",
        ),
        migrations.RemoveField(model_name="leaderboard", name="user",),
        migrations.AddField(
            model_name="leaderboard",
            name="leaderboard_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="user_id_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=255),
        ),
    ]
