# Generated by Django 5.2 on 2025-06-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_transactionhistory_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.option",
            ),
        ),
    ]
