# Generated by Django 5.2 on 2025-06-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_transactionhistory_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("BET", "Bet Placed"),
                    ("WIN", "Winning"),
                    ("LOSS", "Lost Bet"),
                    ("BALANCE_UPDATE", "Balance Update"),
                ],
                default="BET",
                max_length=20,
            ),
        ),
    ]
