# Generated by Django 5.2 on 2025-05-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_totalbalance_wallet_total_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="phone_number",),
        migrations.RemoveField(model_name="profile", name="website",),
    ]
