# Generated by Django 5.2 on 2025-05-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_profile_phone_number_remove_profile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="job",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
