# Generated by Django 5.2 on 2025-06-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_transactionhistory_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="questions/"),
        ),
    ]
