# Generated by Django 5.2 on 2025-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
