# Generated by Django 5.2 on 2025-06-08 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_question_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="amount",),
        migrations.RemoveField(model_name="task", name="completed_at",),
        migrations.RemoveField(model_name="task", name="completed_by",),
        migrations.RemoveField(model_name="task", name="description",),
        migrations.RemoveField(model_name="task", name="is_completed",),
        migrations.RemoveField(model_name="task", name="title",),
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/"),
        ),
        migrations.AddField(
            model_name="news",
            name="image_base64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tasks/"),
        ),
        migrations.AddField(
            model_name="task",
            name="image_base64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_topic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
