# Generated by Django 5.2 on 2025-06-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_task_amount_remove_task_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
