# Generated by Django 5.2 on 2025-06-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_task_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.task",
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.question",
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("BET", "Bet Placed"),
                    ("WIN", "Winning"),
                    ("LOSS", "Lost Bet"),
                    ("BALANCE_UPDATE", "Balance Update"),
                    ("TASK_REWARD", "Task Reward"),
                ],
                default="BET",
                max_length=20,
            ),
        ),
    ]
